config/routes.rb
Rails.application.routes.draw do

  match "/private/uploads/document/:id/:basename.:extension", :controller => 'documents', :action => 'download', via: :get
  resources :documents , only: [:index, :new, :create]
  resources :users, only: [:new, :create]#is that needed?
  get 'signup' => 'users#new' #can be done like that?
  get 'signin' => 'sessions#new' #can be done like that?
  post 'signin' => 'sessions#create' #can be done like that?
  delete 'signout' => 'sessions#destroy' #can be done like that?
  root 'welcome#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :attachment, DocumentUploader
  validates :attachment, presence: true
  validates :name, length: {in: 3..30}
  validates :short_description,
            length: {in: 3..150}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def require_user
    redirect_to signin_path unless current_user
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :require_user
  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)

    if @document.save
      redirect_to documents_path, notice: "Document #{@document.name} added!"
    else
      render 'new'
    end
  end

  def download
    path = "#{request.original_fullpath[1..-1]}"
    send_file path, :disposition => 'attachment', :x_sendfile=>true
  end

  private

  def document_params
    params.require(:document).permit(:name, :short_description, :attachment)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_login(params[:session][:login])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to signin_path, alert: 'Incorrect login/password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/' #redirect to home page
    else
      redirect_to '/signup' #or new_user_path - depends on routes
    end
  end

  private
  def user_params
    params.require(:user).permit(:login,:email,:password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.slim
.form.col-xs-12.col-sm-6
  = bootstrap_form_for @document do |f|
    = f.text_field :name, :placeholder => 'Document name', autofocus: :true
    = f.text_area :short_description, :placeholder => 'Short description'
    = f.file_field :attachment
    = f.submit 'Save'

app/views/documents/index.html.slim
h1
  p Document#index

ul.list-group
  - @documents.each do |doc|
    .col-xs-6.col-sm-4.col-md-3.col-lg-2
      .panel.panel-default.document-short
        .panel-heading
          =doc.name
        .panel-body
          =doc.short_description
        br
        .btn.btn-xs.btn-default
          =link_to 'Download', "#{doc.attachment_url}"

app/views/documents/new.html.slim
= render 'form'
br
.btn.btn-default
  =link_to 'Uploaded documents', documents_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title MapArchive
    = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container.main-container
      nav.navbar.navbar-default.navbar-fixed-top
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
            span.sr-only
              |Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          .navbar-brand
            =link_to 'Map Archive', root_path
        .navbar-collapse.collapse id='navbar'
          ul.nav.navbar-nav
            li
              =link_to 'Home Page', root_path
            -if current_user
              li.dropdown
                /=link_to 'Documents', documents_path
                a data-toggle='dropdown' data-target='#' href='#'
                  |Documents
                  span.caret
                ul.dropdown-menu
                  li
                    =link_to 'View', documents_path
                  li
                    =link_to 'Upload', new_document_path
          .navbar-right.container-fluid
            ul.nav.navbar-nav
              -if current_user
                li
                  =link_to current_user.login
                li
                  =link_to 'Sign out', signout_path, method: 'delete'
              - else
                li
                  =link_to 'Sign in', signin_path
                li
                  =link_to 'Sign up', signup_path

    .row
      .container
        .col-xs-12
          - if flash[:alert]
            .alert.alert-danger
              = flash[:alert]
          - if flash[:notice]
            .alert.alert-info
              = flash[:notice]
          = yield
    .row
      nav.navbar.navbar-default.navbar-fixed-bottom.container-fluid
        .navbar-brand
          |MapArchive

app/views/users/_form.html.slim
.form.col-xs-12.col-sm-6
  - if @user.errors.any?
    h2 = "There are #{pluralize(@user.errors.count, 'error')} errors:"
    ul
      - @user.errors.full_messages.each do |message|
        li = message
  = bootstrap_form_for @user do |f|
    = f.text_field :login, autofocus: :true
    = f.email_field :email
    = f.password_field :password
    = f.submit 'Create account'

app/views/users/new.html.slim
h1 Create new account
- if flash[:notice]
  .alert.alert-info
    = flash[:notice]

= render 'form'

app/views/welcome/index.html.slim
h1 Welcome In Map Archives!

p Map Archive is document archivization tool that storage all types of documents.
  For better collaboration you can also comment and create access groups to each document, and store
  different versions for each group.